version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
      python: 3.x
  pre_build:
    commands:
      - echo Building the AWS for Fluent Bit image
  build:
    commands:
      - export DOCKER_BUILDKIT=1
      # Command to build debug image
      - make debug
      # Command to build your project
      - make release

      - make debug-al2023
      - make release-al2023

      # List the docker images
      - docker images

      # Push the image to ECR with corresponding architecture as the tag.
      - aws ecr create-repository --repository-name amazon/aws-for-fluent-bit-bug-bash --region ${AWS_REGION} || true
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source latest-al2
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source init-latest-al2
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-al2
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-init-al2
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-efs-al2
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-init-efs-al2

      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source latest-al2023
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source init-latest-al2023
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-al2023
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-init-al2023
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-efs-al2023
      - ./scripts/ecr_publish_image.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit --source debug-init-efs-al2023

      # Create manifest list
      - ./scripts/create_docker_manifest.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit-bug-bash --tag latest-al2023
      - ./scripts/create_docker_manifest.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit-bug-bash --tag init-latest-al2023
      - ./scripts/create_docker_manifest.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit-bug-bash --tag debug-al2023
      - ./scripts/create_docker_manifest.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit-bug-bash --tag debug-init-al2023
      - ./scripts/create_docker_manifest.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit-bug-bash --tag debug-efs-al2023
      - ./scripts/create_docker_manifest.sh --aws_account ${AWS_ACCOUNT} --aws_region ${AWS_REGION} --ecr_repo amazon/aws-for-fluent-bit-bug-bash --tag debug-init-efs-al2023

artifacts:
  files:
    - '**/*'
